name: CI

on:
  push:
  workflow_dispatch:

jobs:
  container-test-job:
    runs-on: self-hosted
    container:
      image: openjdk:17-jdk-slim
      
    steps:
      - name: Check for dockerenv file
        run: ls -al