name: CI

on:
  push:
  workflow_dispatch:

jobs:
  container-test-job:
    runs-on: self-hosted
    container:
      image: nexus.dupoiron.com/openjdk:17-jdk-airbus

    steps:
      - name: Check for dockerenv file
        run: ls -al