name: "Hello World Docker Action from private image"

on:
  push:
  workflow_dispatch:

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Hello World Docker
        uses: docker://nexus.dupoiron.com/hello-world:1.0.0-airbus
        with:
          who-to-greet: 'John Doe'