name: "Docker Runner from private image"

on:
  push:
  workflow_dispatch:

jobs:
  hello-world-job:
    runs-on: ubuntu-latest
    container:
      image: nexus.dupoiron.com/hello-world:1.0.0-airbus
      credentials:
        username: ${{  secrets.NEXUS_USERNAME }}
        password: ${{  secrets.NEXUS_PASSWORD }}

    steps:
      - name: List files
        run: ls -la