name: "Docker Action from private image"

on:
  push:
  workflow_dispatch:

jobs:
  hello-world-job:
    runs-on: ubuntu-latest
    steps:
      - name: Hello World Docker
        uses: docker://${{ secrets.NEXUS_USERNAME }}:${{ secrets.NEXUS_PASSWORD }}@nexus.dupoiron.com/hello-world:1.0.0-airbus
        with:
          who-to-greet: 'John Doe'