name: "Docker Action from private image"

on:
  push:
  workflow_dispatch:

jobs:
  hello-world-job:
    runs-on: ubuntu-latest
    steps:
      - name: Docker Login
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }} nexus.dupoiron.com
      - name: Hello World Docker
        uses: docker://user:password@nexus.dupoiron.com/hello-world:1.0.0-airbus
        with:
          who-to-greet: 'Simple user'