name: "Docker Action from private image"

on:
  push:
  workflow_dispatch:

jobs:
  hello-world-docker-image-job:
    runs-on: self-hosted
    steps:
      - name: Hello World Docker
        uses: docker://nexus.dupoiron.com/hello-world:1.0.0-airbus
        with:
          who-to-greet: 'Simple user'