name: "Docker Action from Dockerfile"

on:
  push:
  workflow_dispatch:

jobs:
  hello-world-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Hello World Docker
        uses: ./
        with:
          who-to-greet: 'John Doe'