name: "Docker Runner from private image"

on:
  push:
  workflow_dispatch:

jobs:
  hello-world-job:
    runs-on: self-hosted
    container:
      image: nexus.dupoiron.com/openjdk:17-jdk-airbus
      credentials:
        username: ${{  secrets.NEXUS_USERNAME }}
        password: ${{  secrets.NEXUS_PASSWORD }}
      options: --entrypoint /bin/sh -it

    steps:
      - name: List files
        run: ls -la