name: "Custom Action from private image"

on:
  push:
  workflow_dispatch:

jobs:
  hello-world-custom-action-from-private-image-job:
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: Hello World Docker
        uses: ./action-privateimage
        with:
          who-to-greet: 'John Doe'